[build]
command = "npm run build"

[start]
command = "npm run start:prod"

[deploy]
healthcheckPath = "/v1/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10